### ISSUE TITLE
spec i in tests

### ISSUE THREAD

**Issue by fica99** [fica99/libftprintf#12]
Test 832 (bonus_as_i_prec0val0_was) : FAILED.
    First line of code: {return test("%+5.0i", 0);}
      expected output : "    +"
      your output     : "     +"
      expected (nonprintable as hex) : "    +"
      actual   (nonprintable as hex) : "     +"

Test 833 (bonus_as_i_prec0val0_was_impl) : FAILED.
    First line of code: {return test("%+5.i", 0);}
      expected output : "    +"
      your output     : "     +"
      expected (nonprintable as hex) : "    +"
      actual   (nonprintable as hex) : "     +"

Test 834 (bonus_as_i_prec0val0_waslj) : FAILED.
    First line of code: {return test("%+-5.0i", 0);}
      expected output : "+    "
      your output     : "+     "
      expected (nonprintable as hex) : "+    "
      actual   (nonprintable as hex) : "+     "

Test 835 (bonus_as_i_prec0val0_waslj_impl) : FAILED.
    First line of code: {return test("%+-5.i", 0);}
      expected output : "+    "
      your output     : "+     "
      expected (nonprintable as hex) : "+    "
      actual   (nonprintable as hex) : "+     "

**Comment by OlegMulko** [comment]
OK!
