### ISSUE TITLE
Spec s bug

### ISSUE THREAD

**Issue by fica99** [fica99/libftprintf#25]
Test  76 (s_null_space_padded_over_field_width) : FAILED.
    First line of code: {return test("%2s", NULL);}
      expected output : "(null)"
      your output     : "  "
      expected (nonprintable as hex) : "(null)"
      actual   (nonprintable as hex) : "  "

Test  79 (s_null_space_padded_over_field_width_lj) : FAILED.
    First line of code: {return test("%-3s", NULL);}
      expected output : "(null)"
      your output     : "   "
      expected (nonprintable as hex) : "(null)"
      actual   (nonprintable as hex) : "   "

Test  91 (s_prec_03_no_width_s_null) : FAILED.
    First line of code: {return test("%.03s", NULL);}
      expected output : "(nu"
      your output     : ""
      expected (nonprintable as hex) : "(nu"
      actual   (nonprintable as hex) : ""

Test 113 (s_prec_1_width_3_s_null) : FAILED.
    First line of code: {return test("%3.1s", NULL);}
      expected output : "  ("
      your output     : "   "
      expected (nonprintable as hex) : "  ("
      actual   (nonprintable as hex) : "   "

Test 114 (s_prec_1_width_9_s_null) : FAILED.
    First line of code: {return test("%9.1s", NULL);}
      expected output : "        ("
      your output     : "         "
      expected (nonprintable as hex) : "        ("
      actual   (nonprintable as hex) : "         "

Test 117 (s_prec_1_lj_width_3_s_null) : FAILED.
    First line of code: {return test("%-3.1s", NULL);}
      expected output : "(  "
      your output     : "   "
      expected (nonprintable as hex) : "(  "
      actual   (nonprintable as hex) : "   "

Test 118 (s_prec_1_lj_width_9_s_null) : FAILED.
    First line of code: {return test("%-9.1s", NULL);}
      expected output : "(        "
      your output     : "         "
      expected (nonprintable as hex) : "(        "
      actual   (nonprintable as hex) : "         "

**Comment by fica99** [comment]
Test 3988 (notinsubject_moul_widestr_basic2) : FAILED.
    First line of code: {wchar_t wz[3] = L"@@"; return test("%ls", wz);}
      expected output : "@@"
      your output     : "@"
      expected (nonprintable as hex) : "@@"
      actual   (nonprintable as hex) : "@"

**Comment by fica99** [comment]
Test  91 (s_prec_03_no_width_s_null) : FAILED.
    First line of code: {return test("%.03s", NULL);}
      expected output : "(nu"
      your output     : ""
      expected (nonprintable as hex) : "(nu"
      actual   (nonprintable as hex) : ""

Test 113 (s_prec_1_width_3_s_null) : FAILED.
    First line of code: {return test("%3.1s", NULL);}
      expected output : "  ("
      your output     : "   "
      expected (nonprintable as hex) : "  ("
      actual   (nonprintable as hex) : "   "

Test 114 (s_prec_1_width_9_s_null) : FAILED.
    First line of code: {return test("%9.1s", NULL);}
      expected output : "        ("
      your output     : "         "
      expected (nonprintable as hex) : "        ("
      actual   (nonprintable as hex) : "         "

Test 117 (s_prec_1_lj_width_3_s_null) : FAILED.
    First line of code: {return test("%-3.1s", NULL);}
      expected output : "(  "
      your output     : "   "
      expected (nonprintable as hex) : "(  "
      actual   (nonprintable as hex) : "   "

Test 118 (s_prec_1_lj_width_9_s_null) : FAILED.
    First line of code: {return test("%-9.1s", NULL);}
      expected output : "(        "
      your output     : "         "
      expected (nonprintable as hex) : "(        "
      actual   (nonprintable as hex) : "         "

**Comment by fica99** [comment]
> Test 76 (s_null_space_padded_over_field_width) : FAILED.
> First line of code: {return test("%2s", NULL);}
> expected output : "(null)"
> your output : " "
> expected (nonprintable as hex) : "(null)"
> actual (nonprintable as hex) : " "
> 
> Test 79 (s_null_space_padded_over_field_width_lj) : FAILED.
> First line of code: {return test("%-3s", NULL);}
> expected output : "(null)"
> your output : " "
> expected (nonprintable as hex) : "(null)"
> actual (nonprintable as hex) : " "
> 
> Test 91 (s_prec_03_no_width_s_null) : FAILED.
> First line of code: {return test("%.03s", NULL);}
> expected output : "(nu"
> your output : ""
> expected (nonprintable as hex) : "(nu"
> actual (nonprintable as hex) : ""
> 
> Test 113 (s_prec_1_width_3_s_null) : FAILED.
> First line of code: {return test("%3.1s", NULL);}
> expected output : " ("
> your output : " "
> expected (nonprintable as hex) : " ("
> actual (nonprintable as hex) : " "
> 
> Test 114 (s_prec_1_width_9_s_null) : FAILED.
> First line of code: {return test("%9.1s", NULL);}
> expected output : " ("
> your output : " "
> expected (nonprintable as hex) : " ("
> actual (nonprintable as hex) : " "
> 
> Test 117 (s_prec_1_lj_width_3_s_null) : FAILED.
> First line of code: {return test("%-3.1s", NULL);}
> expected output : "( "
> your output : " "
> expected (nonprintable as hex) : "( "
> actual (nonprintable as hex) : " "
> 
> Test 118 (s_prec_1_lj_width_9_s_null) : FAILED.
> First line of code: {return test("%-9.1s", NULL);}
> expected output : "( "
> your output : " "
> expected (nonprintable as hex) : "( "
> actual (nonprintable as hex) : " "

FIXED

**Comment by fica99** [comment]
> Test 91 (s_prec_03_no_width_s_null) : FAILED.
> First line of code: {return test("%.03s", NULL);}
> expected output : "(nu"
> your output : ""
> expected (nonprintable as hex) : "(nu"
> actual (nonprintable as hex) : ""
> 
> Test 113 (s_prec_1_width_3_s_null) : FAILED.
> First line of code: {return test("%3.1s", NULL);}
> expected output : " ("
> your output : " "
> expected (nonprintable as hex) : " ("
> actual (nonprintable as hex) : " "
> 
> Test 114 (s_prec_1_width_9_s_null) : FAILED.
> First line of code: {return test("%9.1s", NULL);}
> expected output : " ("
> your output : " "
> expected (nonprintable as hex) : " ("
> actual (nonprintable as hex) : " "
> 
> Test 117 (s_prec_1_lj_width_3_s_null) : FAILED.
> First line of code: {return test("%-3.1s", NULL);}
> expected output : "( "
> your output : " "
> expected (nonprintable as hex) : "( "
> actual (nonprintable as hex) : " "
> 
> Test 118 (s_prec_1_lj_width_9_s_null) : FAILED.
> First line of code: {return test("%-9.1s", NULL);}
> expected output : "( "
> your output : " "
> expected (nonprintable as hex) : "( "
> actual (nonprintable as hex) : " 
FIXED

**Comment by OlegMulko** [comment]
./test "*_s_*"

Tests completed. 120/120 tests passed.

OK!
